### ISSUE TITLE
Add UERANSIM template ID

### ISSUE THREAD

**Issue by alvarocurt** [6G-SANDBOX/6G-Sandbox-Sites#1]
Add variable
```yaml
site_one_templates:
  ueransim:
    id: 71
```
